# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "feat/cicd" ]
    tags:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Vet
      run: go vet -v ./...

  tag_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.git-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - id: git-version
        run: echo "version=$(git describe)" >> $GITHUB_OUTPUT

  container-latest:
    if: ${{ contains(fromJson('["main"]'), github.ref_name) }}
    needs:
      - tag_version
      - build
    uses: ./.github/workflows/containers.yml
    with:
      tag-name: latest

  container-release:
    if: ${{ github.ref_type == 'tag' && startsWith('v', github.ref_name)  }}
    needs:
      - tag_version
      - build
    uses: ./.github/workflows/containers.yml
    with:
      tag-name: ${{ needs.tag_version.outputs.version }}
